[package]
name = "wasi-crypto-example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasi-crypto-guest = { path = "../wasi-crypto/implementations/bindings/rust" }